### ISSUE TITLE
Switch to building the static site on heroku rather than travis

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/webhook-manager#14]
Now the CSVs are being generated in everypolitician-data we should in theory be able to create the static site by running `wget` against the heroku version of viewer-sinatra.

**Comment by tmtmtmtm** [comment]
With the new heroku limits, I'm guessing we don't actually _want_ to do this now?

**Comment by chrismytton** [comment]
Yep, we don't want it because of Heroku limits, and we haven't really needed it - Travis seems to be doing the job just fine.
